AWSTemplateFormatVersion: 2010-09-09
Parameters:
  TemplatesBucketName:
    Description: Globally unique S3 bucket name
    Type: String
  OutputBucketName:
    Description: Globally unique S3 bucket name
    Type: String
  TestBucketName:
    Description: Globally unique S3 bucket name
    Type: String
Resources:
  TemplatesBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref TemplatesBucketName
  OutputBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref OutputBucketName
  TestBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref TestBucketName
