AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A site generator that transforms Markdown into HTML
Parameters:
  InputBucketName:
    Type: String
  OutputBucketName:
    Type: String
Resources:
  SiteGen:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: python3.6
      Timeout: 10
      CodeUri: ./src
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref InputBucketName
        - S3CrudPolicy:
            BucketName: !Ref OutputBucketName
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref InputBucket
            Events: s3:ObjectCreated:*
      Environment:
        Variables:
          OUTPUT_BUCKET: !Ref OutputBucket
  InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref InputBucketName
  OutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref OutputBucketName
